#########################################################################
# Title:         Sandbox: Sanity Check | Bizbox Check                  #
# Author(s):     desimaniac, salty                                      #
# URL:           https://github.com/jeremiahg7/Sandbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Check if 'bizbox' folder is present"
  ansible.builtin.stat:
    path: "/srv/git/bizbox"
  register: saltbox_path

- name: "Fail when 'bizbox' folder does not exist"
  ansible.builtin.fail:
    msg: "Bizbox installation is required before running the Sandbox roles."
  when: not saltbox_path.stat.exists
