#########################################################################
# Title:         Sandbox: Jellyseerr Role                               #
# Author(s):     salty                                                  #
# URL:           https://github.com/jeremiahg7/Sandbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Execute Jellyseerr roles"
  ansible.builtin.include_tasks: main2.yml
  vars:
    jellyseerr_name: "{{ role }}"
  with_items: "{{ jellyseerr_instances }}"
  loop_control:
    loop_var: role
