#########################################################################
# Title:         Sandbox: Plex Patrol Role                              #
# Author(s):     l3uddz, salty                                          #
# URL:           https://github.com/jeremiahg7/Sandbox                    #
# --                                                                    #
#########################################################################
#                   GNU General Public License v3.0                     #
#########################################################################
---
- name: "Execute Plex Patrol roles"
  ansible.builtin.include_tasks: main2.yml
  vars:
    plex_name: "{{ role }}"
  with_items: "{{ plex_instances }}"
  loop_control:
    loop_var: role
